In [1]:
import numpy as np
import pandas as pd
import xarray as xr

In [2]:
# 0p1 = 2.54 mm per day
# 1p0 = 25.4 mm per day
# 2p5 = 63.5 mm per day

list_ds = []
list_exp_name = []

base_dir = '/glade/campaign/ral/hap/ksha/GWC_results/MET/'

exp_names = ['B3H', 'B6H', 'GDAS', 'C404']
thres_names = ['_0p1.txt', '_1p0.txt', '_2p5.txt']

fn_lists = ['B3H_1p0.txt', 'C404_1p0.txt']

num_cols = ["object_count", "total_object_area", "mean_object_area", "mean_intensity90"]

## MODE summary statistics

In [4]:
for exp in exp_names:
    for thres in thres_names:
        fn = base_dir + exp + thres
        list_exp_name.append(exp + thres)
        
        df = pd.read_csv(fn, na_values=["NA"])
        
        # Parse the valid_time column (format matches YYYYMMDD_HHMMSS)
        df["valid_time"] = pd.to_datetime(df["valid_time"], format="%Y%m%d_%H%M%S")
        
        # Convert numeric columns (NA already became NaN)
        df[num_cols] = df[num_cols].apply(pd.to_numeric, errors="coerce")
        
        # If you want object_count as a nullable integer:
        df["object_count"] = df["object_count"].astype("Int64")
        
        df = df.copy()
        df["month"] = df["valid_time"].dt.month  # 1–12
        
        # 12-month climatological mean of numeric columns (NaNs ignored)
        monthly_mean = (
            df.groupby("month")[['total_object_area', 'mean_object_area', 'mean_intensity90']]
              .mean(numeric_only=True)
              .reindex(range(1, 13))
        )
        
        #monthly_mean = monthly_mean.drop(['object_count'])
        
        # 12-month total number of objects across all years
        monthly_total = (
            df.groupby("month")["object_count"]
              .sum(min_count=1)          # keep all-NA months as NaN
              .reindex(range(1, 13))
              .rename("total_objects")
        )
        
        df_month = pd.concat([monthly_mean, monthly_total], axis=1)
        ds = xr.Dataset.from_dataframe(df_month)
        list_ds.append(ds)

In [5]:
ds_all = xr.concat(list_ds, dim='experiment')
ds_all = ds_all.assign_coords({'experiment': list_exp_name})

In [6]:
ds_all = ds_all.load()

In [8]:
ds_all = ds_all.chunk({'month': 12, 'experiment': 12})
save_name = base_dir + 'object_verif_all.zarr'
# ds_all.to_zarr(save_name, mode='w', consolidated=True, compute=True)
print(save_name)

/glade/campaign/ral/hap/ksha/GWC_results/MET/object_verif_all.zarr


/glade/work/ksha/miniconda3/envs/credit/lib/python3.11/site-packages/xarray/conventions.py:232: SerializationWarning: variable None has data in the form of a dask array with dtype=object, which means it is being loaded into memory to determine a data type that can be safely stored on disk. To avoid this, coerce this variable to a fixed-size dtype with astype() before saving it.
  warnings.warn(


In [12]:
save_name = base_dir + 'object_verif_all.zarr'
ds_test = xr.open_zarr(save_name)

In [14]:
ds_test = ds_test.isel(month=[6, 7, 8])

In [16]:
ds_test['experiment'].values

array(['B3H_0p1.txt', 'B3H_1p0.txt', 'B3H_2p5.txt', 'B6H_0p1.txt',
       'B6H_1p0.txt', 'B6H_2p5.txt', 'GDAS_0p1.txt', 'GDAS_1p0.txt',
       'GDAS_2p5.txt', 'C404_0p1.txt', 'C404_1p0.txt', 'C404_2p5.txt'],
      dtype='<U12')

In [21]:
ds_test['mean_object_area'].values.astype(int)

array([[1654, 1548, 2684],
       [ 758,  837, 1246],
       [ 404,  417,  826],
       [2374, 2642, 2632],
       [ 754,  902, 1078],
       [ 347,  383,  643],
       [2338, 2632, 2942],
       [ 863,  899, 1085],
       [ 342,  486,  412],
       [2173, 2029, 2314],
       [ 797,  707,  937],
       [ 460,  675,  717]])

### CONUS404 vs AI-based LAM

In [5]:
rmse_cols = ["object_count", "mean_object_area", "mean_intensity90"]

In [6]:
list_ds = []
list_exp_name = []
list_thres_name = []


for thres in thres_names:
    # -----------------------------
    # Read target: C404
    # -----------------------------
    fn_target = base_dir + 'C404' + thres

    df_target = pd.read_csv(fn_target, na_values=["NA"])
    df_target["valid_time"] = pd.to_datetime(df_target["valid_time"], format="%Y%m%d_%H%M%S")
    df_target[num_cols] = df_target[num_cols].apply(pd.to_numeric, errors="coerce")
    df_target["object_count"] = df_target["object_count"].astype("Int64")
    
    # Only keep JJA
    df_target_jja = df_target[df_target["valid_time"].dt.month.isin([6, 7, 8])]

    for exp in exp_names[:-1]:

        # -----------------------------
        # Read prediction
        # -----------------------------
        fn_pred = base_dir + exp + thres

        df_pred = pd.read_csv(fn_pred, na_values=["NA"])
        df_pred["valid_time"] = pd.to_datetime(df_pred["valid_time"], format="%Y%m%d_%H%M%S")
        df_pred[num_cols] = df_pred[num_cols].apply(pd.to_numeric, errors="coerce")
        df_pred["object_count"] = df_pred["object_count"].astype("Int64")

        # Only keep JJA
        df_pred_jja = df_pred[df_pred["valid_time"].dt.month.isin([6, 7, 8])]

        # -----------------------------
        # Match prediction and target by valid_time
        # -----------------------------
        df_merge = pd.merge(
            df_pred_jja[["valid_time"] + rmse_cols],
            df_target_jja[["valid_time"] + rmse_cols],
            on="valid_time", how="inner", suffixes=("_pred", "_target")
        )
        # # -----------------------------
        # # Compute metrics
        # # -----------------------------
        metrics = {}
        
        # -------- Continuous metrics per variable --------
        for var in rmse_cols:
            pred   = df_merge[f"{var}_pred"].astype(float)
            target = df_merge[f"{var}_target"].astype(float)
        
            valid = pred.notna() & target.notna()
            p, t = pred[valid], target[valid]
            n = len(p)
        
            if n:
                diff = p - t
                metrics[f"rmse_{var}"] = float(np.sqrt((diff ** 2).mean()))
                metrics[f"mae_{var}"]  = float(diff.abs().mean())
                metrics[f"bias_{var}"] = float(diff.mean())
                # Pearson correlation; undefined if either series is constant
                if n > 1 and p.std() > 0 and t.std() > 0:
                    metrics[f"corr_{var}"] = float(p.corr(t))
                else:
                    metrics[f"corr_{var}"] = np.nan
            else:
                for m in ("rmse", "mae", "bias", "corr"):
                    metrics[f"{m}_{var}"] = np.nan
            metrics[f"n_{var}"] = n
        
        # -----------------------------
        # Convert one experiment-threshold result to xr.Dataset
        # -----------------------------
        ds_RMSE = xr.Dataset(
            data_vars={k: xr.DataArray(v) for k, v in metrics.items()}
        )

        list_ds.append(ds_RMSE)
        list_exp_name.append(exp)
        list_thres_name.append(thres.replace(".txt", "").replace("_", ""))

# ------------------------------------------------
# Combine all results
# ------------------------------------------------
ds_all = xr.concat(
    list_ds,
    dim=pd.MultiIndex.from_arrays(
        [list_exp_name, list_thres_name],
        names=["experiment", "threshold"]
    )
)

ds_all = ds_all.unstack()

print(ds_all)

<xarray.Dataset> Size: 1kB
Dimensions:                (concat_dim: 9)
Coordinates:
  * concat_dim             (concat_dim) object 72B ('B3H', '0p1') ... ('GDAS'...
Data variables: (12/15)
    rmse_object_count      (concat_dim) float64 72B 8.195 7.933 ... 1.376 1.315
    mae_object_count       (concat_dim) float64 72B 6.521 6.327 ... 0.8475
    bias_object_count      (concat_dim) float64 72B -5.949 -5.945 ... -0.2034
    corr_object_count      (concat_dim) float64 72B 0.2276 0.3452 ... 0.167
    n_object_count         (concat_dim) int64 72B 315 330 350 196 ... 57 66 59
    rmse_mean_object_area  (concat_dim) float64 72B 2.872e+03 ... 726.3
    ...                     ...
    n_mean_object_area     (concat_dim) int64 72B 315 330 350 196 ... 57 66 59
    rmse_mean_intensity90  (concat_dim) float64 72B 7.932 10.85 ... 40.76 31.78
    mae_mean_intensity90   (concat_dim) float64 72B 5.625 7.576 ... 32.7 25.05
    bias_mean_intensity90  (concat_dim) float64 72B 0.1652 3.788 ... -10.4
    cor

In [25]:
ds_all['corr_mean_intensity90'].values

array([0.32613216, 0.11056615, 0.06799628, 0.26885461, 0.2056217 ,
       0.11252162, 0.3948772 , 0.23495105, 0.36917124])

In [10]:
ds_all['mae_mean_intensity90'].values

array([ 5.62453968,  7.57606061,  7.37771429, 16.62566327, 17.18315556,
       17.53399194, 24.96052632, 32.69787879, 25.04813559])